# WEB SCRAPING – ASSIGNMENT 4:

1. Scrape the details of most viewed videos on YouTube from Wikipedia.Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videosYou need to find following details:

      A) Rank

      B) Name

      C) Artist

      D) Upload date 

      E) Views

In [2]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [3]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url=' https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [4]:
#import required libraries
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as Ec
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException

In [11]:
#Scraping all the required columns and framing them in form of lists:
rank=[]
name=[]
artist=[]
upload_date=[]
views=[]
try:
    r=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[1]')
    n=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[2]')
    a=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[3]')
    d=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[5]')
    v=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td[4]')
    for i in r:
        rank.append(i.text)
    for i in n:
        name.append(i.text)
    for i in a:
        artist.append(i.text)
    for i in d:
        upload_date.append(i.text)
    for i in v:
        views.append(i.text)
except NoSuchElementException :
    loop=[rank,name,artist,upload_date,views]
    for i in loop:
        i.append('_') 
except TimeoutException as e:
    print('Exception Raised: ',e)

In [14]:
#selecting the required data and checking the length of all the lists framed above:
rank=rank[0:30]
name=name[0:30]
artist=artist[0:30]
upload_date=upload_date[0:30]
views=views[0:30]
print(len(rank),len(name),len(artist),len(upload_date),len(views))

30 30 30 30 30

In [15]:
#Creating a data frame using the above data:
df=pd.DataFrame({'Rank':rank,'Video_name':name,'Artist':artist,'Upload_date':upload_date,'Views':views})
df

,Rank,Video_name,Artist,Upload_date,Views
0,10.33,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.33
1,7.78,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.78
2,6.23,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.23
3,5.65,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.65
4,5.44,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.44
5,5.10,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.10
6,4.56,"""Learning Colors – Colorful Eggs on a Farm""[21]",Miroshka TV,"February 27, 2018",4.56
7,4.51,"""Phonics Song with Two Words""[22]",ChuChu TV,"March 6, 2014",4.51
8,4.49,"""Uptown Funk""[23]",Mark Ronson,"November 19, 2014",4.49
9,4.49,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,"January 31, 2012",4.49
10,4.36,"""Gangnam Style""[25]",Psy,"July 15, 2012",4.36
11,3.89,"""Dame Tu Cosita""[30]",El Chombo,"April 5, 2018",3.89
12,3.79,"""Wheels on the Bus""[31]",Cocomelon – Nursery Rhymes,"May 24, 2018",3.79
13,3.66,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.66
14,3.54,"""Roar""[33]",Katy Perry,"September 5, 2013",3.54
15,3.53,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.53
16,3.52,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.52
17,3.42,"""Thinking Out Loud""[36]",Ed Sheeran,"October 7, 2014",3.42
18,3.27,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.27
19,3.25,"""Girls Like You""[38]",Maroon 5,"May 31, 2018",3.25
20,3.25,"""Faded""[39]",Alan Walker,"December 3, 2015",3.25
21,3.24,"""Dark Horse""[40]",Katy Perry,"February 20, 2014",3.24
22,3.19,"""Let Her Go""[41]",Passenger,"July 25, 2012",3.19
23,3.18,"""Bailando""[42]",Enrique Iglesias,"April 11, 2014",3.18
24,3.18,"""Lean On""[43]",Major Lazer,"March 22, 2015",3.18
25,3.17,"""Baa Baa Black Sheep""[44]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.17
26,3.15,"""Shake It Off""[45]",Taylor Swift,"August 18, 2014",3.15
27,3.11,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.11
28,3.08,"""Waka Waka (This Time for Africa)""[47]",Shakira,"June 4, 2010",3.08
29,3.05,"""Mi Gente""[48]",J Balvin,"June 29, 2017",3.05

In [ ]:
driver.close()

2. Scrape the details team India’s international fixtures from bcci.tv.Url = https://www.bcci.tv/.You need to find following details:

A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [16]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [18]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url='https://www.bcci.tv/'
driver.get(url)

In [24]:
#go to main menu and click:
menu=driver.find_element_by_xpath('/html/body/nav/div/button')
menu.click()
#Click international:
international=driver.find_element_by_xpath('/html/body/nav/div/div[2]/ul[1]/li[2]')
international.click()

In [34]:
#selecting the match center for each program:
mtctr=driver.find_elements_by_xpath('//a[@class="match-center-btn ng-scope"]')
url=[]
for i in mtctr:
    url.append(i.get_attribute('href'))
    
len(url)

8

In [41]:
#scraping title,date and time from the url page itself and framing them in list:
title=[]
series=[]
place=[]
date=[]
time=[]
m=driver.find_elements_by_xpath('//span[@class="ng-binding"]')
d=driver.find_elements_by_xpath('//h5[@class="ng-binding"]')
t=driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]')
for i in m:
    title.append(i.text)
for i in d:
    date.append(i.text)
for i in t:
    time.append(i.text.split('I').pop(0))

In [43]:
#scraping series,place from each page and framing them in list:
series=[]
place=[]
for i in url:
    driver.get(i)
  
    try:
        s=driver.find_element_by_xpath('//div[@class="widgetContent"]/ul/li[2]/span[2]')
        p=driver.find_element_by_xpath('//div[@class="widgetContent"]/ul/li[3]/span[2]')
        series.append(s.text)
        place.append(p.text)
    except NoSuchElementException:
        loop=[series,place]
        for i in loop:
            i.append('_')

In [44]:
print(len(title),len(date),len(time),len(series),len(place)) #checking the length of all the lists

8 8 8 8 8

In [46]:
#Creating a dataframe:
df=pd.DataFrame({'Match_title':title,'Series':series,'Place':place,'Date':date,'Time(IST)':time})
df

,Match_title,Series,Place,Date,Time(IST)
0,ICC WOMENS WORLD CUP 2022,India Women VS Australia Women,EDEN PARK,19 MAR 2022,6:30 AM
1,ICC WOMENS WORLD CUP 2022,India Women VS Bangladesh Women,SEDDON PARK,22 MAR 2022,6:30 AM
2,ICC WOMENS WORLD CUP 2022,India Women VS South Africa Women,HAGLEY OVAL,28 MAR 2022,6:30 AM
3,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,India VS South Africa,MA CHIDAMBARAM STADIUM,9 JUN 2022,7:30 PM
4,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,India VS South Africa,M CHINNASWAMY STADIUM,12 JUN 2022,7:30 PM
5,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,India VS South Africa,VIDARBHA CRICKET ASSOCIATION STADIUM,14 JUN 2022,7:30 PM
6,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,India VS South Africa,SAURASHTRA CRICKET ASSOCIATION STADIUM,17 JUN 2022,7:30 PM
7,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,India VS South Africa,ARUN JAITLEY STADIUM,19 JUN 2022,7:30 PM

In [ ]:
driver.close()

3. Scrape the details of selenium exception from guru99.com.Url = https://www.guru99.com/. You need to find following details:

      A) Name
      
      B) Description
      
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [47]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [48]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url='https://www.guru99.com/'
driver.get(url)

In [49]:
#clicking the selinium button
se=driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[2]/span[8]/a/img')
se.click()

In [50]:
#getting the exception handling tutorial
excep=driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a')
excep.click()

In [52]:
#scraping the name and description and framming them in lists:
name=[]
description=[]
try:
    n=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
    d=driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
    for i in n:
        name.append(i.text)
    for i in d:
        description.append(i.text)
except NoSuchElementException:
        loop=[name,description]
        for i in loop:
            i.append('_')

In [53]:
print(len(name),len(description))#checking the length of lists

41 41

In [55]:
#creating a Dataframe:
df=pd.DataFrame({'Exception_Name':name,'Description':description})
df

,Exception_Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [56]:
driver.close()#closing the driver

4. Scrape the details of State-wise GDP of India from statisticstime.com.Url = http://statisticstimes.com/
   You have to find following details:
   
    A) Rank
    
    B) State
    
    C) GSDP
    
    D) GSDP
    
    E) Share
    
    F) GDP($ billion)
    
   Note: - From statisticstimes home page you have to reach to economy page through code.

In [60]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [61]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url=' http://statisticstimes.com/ '
driver.get(url)

In [63]:
economy=driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()#clicking the economy button
economy_india=driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
economy_india.click()#In ecocnomy clicking the INDIA button

In [64]:
gdp_states=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
gdp_states.click()#clicking the GDP of indian states

In [67]:
#scraping the rank,state,gsdp,share and gdp of each state and framming them in lists:
rank=[]
state=[]
gsdp1=[]
gsdp2=[]
share=[]
gdp=[]
try:
    r=driver.find_elements_by_xpath('//td[@class="data1"]')
    st=driver.find_elements_by_xpath('//td[@class="name"]')
    gsd1=driver.find_elements_by_xpath('//table[@class="display dataTable"]/tbody/tr/td[3]')
    gsd2=driver.find_elements_by_xpath('//td[@class="data sorting_1"]')
    s=driver.find_elements_by_xpath('//table[@class="display dataTable"]/tbody/tr/td[5]')
    gp=driver.find_elements_by_xpath('//table[@class="display dataTable"]/tbody/tr/td[6]')
    for i in r:
        rank.append(i.text)
    for i in st:
        state.append(i.text)
    for i in gsd1:
        gsdp1.append(i.text)
    for i in gsd2:
        gsdp2.append(i.text)
    for i in s:
        share.append(i.text)
    for i in gp:
        gdp.append(i.text)
except NoSuchElementException:
        loop=[rank,state,gsdp1,gsdp2,share,gdp]
        for i in loop:
            i.append('_')

In [68]:
print(len(rank),len(state),len(gsdp1),len(gsdp2),len(share),len(gdp))#checking the length of each list

68 68 66 66 66 66

In [69]:
#collecting the required data in lists and creating a dataframe:
rank=rank[0:33]
state=state[0:33]
gsdp1=gsdp1[0:33]
gsdp2=gsdp2[0:33]
share=share[0:33]
gdp=gdp[0:33]
df=pd.DataFrame({'Rank':rank,'State':state,'GSDP':gsdp1,'GSDP':gsdp2,'Share':share,'GDP($ billion)':gdp})
df

   Rank                      State       GSDP   Share GDP($ billion)
0     1                Maharashtra  2,632,792  13.94%        399.921
1     2                 Tamil Nadu  1,630,208   8.63%        247.629
2     3              Uttar Pradesh  1,584,764   8.39%        240.726
3     4                    Gujarat  1,502,899   7.96%        228.290
4     5                  Karnataka  1,493,127   7.91%        226.806
5     6                West Bengal  1,089,898   5.77%        165.556
6     7                  Rajasthan    942,586   4.99%        143.179
7     8             Andhra Pradesh    862,957   4.57%        131.083
8     9                  Telangana    861,031   4.56%        130.791
9    10             Madhya Pradesh    809,592   4.29%        122.977
10   11                     Kerala    781,653   4.14%        118.733
11   12                      Delhi    774,870   4.10%        117.703
12   13                    Haryana    734,163   3.89%        111.519
13   14                      Bihar    530,363   2.81%         80.562
14   15                     Punjab    526,376   2.79%         79.957
15   16                     Odisha    487,805   2.58%         74.098
16   17                      Assam    315,881   1.67%         47.982
17   18               Chhattisgarh    304,063   1.61%         46.187
18   19                  Jharkhand    297,204   1.57%         45.145
19   20                Uttarakhand    245,895   1.30%         37.351
20   21            Jammu & Kashmir    155,956   0.83%         23.690
21   22           Himachal Pradesh    153,845   0.81%         23.369
22   23                        Goa     73,170   0.39%         11.115
23   24                    Tripura     49,845   0.26%          7.571
24   25                 Chandigarh     42,114   0.22%          6.397
25   26                 Puducherry     34,433   0.18%          5.230
26   27                  Meghalaya     33,481   0.18%          5.086
27   28                     Sikkim     28,723   0.15%          4.363
28   29                    Manipur     27,870   0.15%          4.233
29   30                   Nagaland     27,283   0.14%          4.144
30   31          Arunachal Pradesh     24,603   0.13%          3.737
31   32                    Mizoram     22,287   0.12%          3.385
32   33  Andaman & Nicobar Islands          -       -              -

In [70]:
driver.close()

5. Scrape the details of trending repositories on Github.com.Url = https://github.com/.You have to find the following details:
       A) Repository title
       B) Repository description
       C) Contributors count
       D) Language used

In [1]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [2]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url='https://github.com/ '
driver.get(url)

In [3]:
# menu_bar=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[1]/div[2]/button')
 #    menu_bar.click()
explore=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary')
explore.click()
trending=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
trending.click()

In [4]:
#getting all the link id's for scraping the data
url=[]
btn=driver.find_elements_by_xpath('//h1[@class="h3 lh-condensed"]/a')

for i in btn:
    url.append(i.get_attribute('href'))
    
len(url)

25

In [5]:
#scraping title from the url's list above
h=[]
for i in url:
    h.append(i.split('.com/').pop(1))
len(h)

25

In [6]:
#scraping the description
rd=[]
description=driver.find_elements_by_xpath('//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for i in description:
    rd.append(i.text)

len(rd)

25

In [9]:
#scraping the language data from the above url
lang=[]
language=driver.find_elements_by_xpath('//span[@itemprop="programmingLanguage"]')
for i in language:
    lang.append(i.text)
lang.insert(7,"_")
lang.insert(9,"_")
lang.insert(10,"_")
lang.insert(22,"_")
len(lang)

25

In [10]:
#scraping the no of contribution to each link and framing them in list
c1=[]
cont=[]
for i in url:
    driver.get(i)
    time.sleep(5)
    try:
        con=driver.find_elements_by_xpath('//h2[@class="h4 mb-3"]/a/span')
        for j in con:
                 cont.append(j.text)
    except NoSuchElementException :
        loop=[cont]
        for i in loop:
            i.append('_')
    except TimeoutException as e:
        print('Exception Raised: ',e)

In [28]:
#slicing the list to get the wanted elements
c1=[]
a1=[0,2,3,6,9,12,15,17,20,22,23,26,28,31,34,35,37,40,43,45,48,49,51,52]
for i in a1:
    c1.append(cont[i])
c1.insert(24,'_')
len(c1)

25

In [29]:
#creating data frame
df=pd.DataFrame({'Repository_title':h,'Repository_description':rd,'Contributors_count':c1,'Languages':lang})
df

,Repository_title,Repository_description,Contributors_count,Languages
0,CodeEditApp/CodeEdit,CodeEdit App for macOS – Elevate your code edi...,18,Swift
1,microsoft/routeros-scanner,Tool to scan for RouterOS (Mikrotik) forensic ...,3,Python
2,ToolJet/ToolJet,Extensible low-code framework for building bus...,40,JavaScript
3,pedroslopez/whatsapp-web.js,A WhatsApp client library for NodeJS that conn...,2.2k,JavaScript
4,ocornut/imgui,Dear ImGui: Bloat-free Graphical User interfac...,281,C++
5,Dreamacro/clash,A rule-based tunnel in Go.,75,Go
6,bitcoin/bitcoin,Bitcoin Core integration/staging tree,855,C++
7,arthurspk/guiadevbrasil,GUIA EXTENSO DE PROGRAMAÇÃO:,25,_
8,lxgr-linux/pokete,A terminal based Pokemon like game,2,Python
9,PKUFlyingPig/cs-self-learning,计算机自学指南,22,_
10,johnthebrit/CertificationMaterials,A collection of materials related to my certif...,2,_
11,freddier/hyperblog,Un blog increíble para el curso de Git y Githu...,278,HTML
12,openmlsys/openmlsys-zh,《Machine Learning Systems: Design and Implemen...,21,TeX
13,kabinspace/AstroVim,AstroVim is an aesthetic and feature-rich neov...,11,Lua
14,rust-lang/rust,Empowering everyone to build reliable and effi...,"3,682",Rust
15,public-apis/public-apis,A collective list of free APIs,"1,269",Python
16,RanKKI/LawRefBook,中华人民共和国法律手册,3,Swift
17,vnpy/vnpy,基于Python的开源量化交易平台开发框架,117,Python
18,coolsnowwolf/lede,Lean's OpenWrt source,289,C
19,google-research/kubric,A data generation pipeline for creating semi-r...,8,Python
20,2dust/v2rayN,"A V2Ray client for Windows, support Xray core ...",17,C#
21,TheAlgorithms/Rust,All Algorithms implemented in Rust,93,Rust
22,dair-ai/ML-Course-Notes,🎓 Sharing course notes on all topics related t...,"3,487",_
23,trustwallet/assets,"A comprehensive, up-to-date collection of info...",898,Go
24,home-assistant/core,🏡 Open source home automation that puts local ...,_,Python

In [31]:
driver.close()

6. Scrape the details of top 100 songs on billiboard.com.Url = https:/www.billboard.com/ .You have to find the following details:

    A) Song name
    
    B) Artist name
    
    C) Last week rank 
    
    D) Peak rank
    
    E) Weeks on board
    
   Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [80]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [81]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url='https:/www.billboard.com/  '
driver.get(url)

In [83]:
billboard=driver.find_element_by_xpath('/html/body/div[4]/header/div[2]/div/nav/ul/li[1]/a')
billboard.click()#CLICKING ON TOP 100 SONGS

In [84]:
#SCRAPING DATA FROM THE URL ABOVE AND PUTTING THEM IN LISTS:
song=[]
artist=[]
lastweek=[]
peak=[]
weekson=[]

try:
    s=driver.find_elements_by_xpath('//LI[@class="lrv-u-width-100p"]/ul/lI/H3')
    a=driver.find_elements_by_xpath('//LI[@class="lrv-u-width-100p"]/ul/lI/span')
    for i in s:
        song.append(i.text)
    for i in a:
        artist.append(i.text)
except NoSuchElementException:
        loop=[song,artist]
        for i in loop:
            i.append('_')

In [88]:
print(len(song),len(artist))#CHECKING THE LENGTH OF ALL THe lists

100 400

In [93]:
#USING SLICING TO GET REQUIRED DATA AND CREATING A DATAFRAME USING THOSE LISTS:
a=[]
a=artist[0:400:4]
lastweek=artist[1:400:4]
peak=artist[2:400:4]
weekson=artist[3:400:4]
df=pd.DataFrame({"Song_Name":song,"Artist":a,"lASTWEEK_RANK":lastweek,"PEAK_RANK":peak,"wEEKS_ON_BOARD":weekson})
df

,Song_Name,Artist,lASTWEEK_RANK,PEAK_RANK,wEEKS_ON_BOARD
0,Heat Waves,Glass Animals,1,1,60
1,We Don't Talk About Bruno,"Carolina Gaitan, Mauro Castillo, Adassa, Rhenz...",2,1,11
2,Super Gremlin,Kodak Black,4,3,18
3,abcdefu,GAYLE,3,3,16
4,Stay,The Kid LAROI & Justin Bieber,5,1,35
...,...,...,...,...,...
95,Evil Twins,King Von & Lil Durk,-,96,1
96,Trust Nothing,King Von Featuring Moneybagg Yo,-,97,1
97,Iffy,Chris Brown,92,71,8
98,Closer,Saweetie Featuring H.E.R.,98,89,4
99,When I'm Gone,Alesso / Katy Perry,91,90,4

In [ ]:
driver.close()

7. Scrape the details of Data science recruiters from naukri.com.Url = https://www.naukri.com/ .You have to find the following details:

    A) Name
    
    B) Designation
    
    C) Company
    
    D) Skills they hire for
    
    E) Location
    
    Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
    click on search. All this should be done through code

In [1]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [8]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)

In [9]:
#in url clicking the recruiters page:
url=' https://www.naukri.com/browse-jobs'
driver.get(url)
recruiters=driver.find_element_by_xpath('/html/body/div[1]/div/ul/li[2]')
recruiters.click()

In [11]:
#In recruitrs url sending skills as data science and search all the recruiters using that skills: 
url2='https://www.naukri.com/hr-recruiters-consultants'
driver.get(url2)
skill=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
skill.send_keys('Data Science')
search=driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
search.click()

In [18]:
#Scraping all the page 1 data and putting them in lists
name1=[]
designation1=[]
company1=[]
skills1=[]
location1=[]
try:
    n=driver.find_elements_by_xpath('//span[@class="fl ellipsis"]')
    d=driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')
    c=driver.find_elements_by_xpath('//a[@class="ellipsis"]')
    s=driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]')
    l=driver.find_elements_by_xpath('//small[@class="ellipsis"]')
    for i in n:
        name1.append(i.text)
    for i in d:
        designation1.append(i.text)
    for i in c:
        company1.append(i.text)
    for i in s:
        skills1.append(i.text)
    for i in l:
        location1.append(i.text)
except NoSuchElementException:
    loop=[name1,designation1,company1,skills1,location1]
    for i in loop:
        i.append('_')

In [19]:
next_btn=driver.find_element_by_xpath('//button[@class="grayBtn"]')#finding the search button element using xpath
next_btn.click()#clicking the next button

In [20]:
#scraping all the othr pages data and putting them in list
name=[]
designation=[]
company=[]
skills=[]
location=[]


for i in range(50):
    print('scraping page ',i+1)
    try:
        n=driver.find_elements_by_xpath('//span[@class="fl ellipsis"]')
        d=driver.find_elements_by_xpath('//span[@class="ellipsis clr"]')
        c=driver.find_elements_by_xpath('//a[@class="ellipsis"]')
        s=driver.find_elements_by_xpath('//div[@class="hireSec highlightable"]')
        l=driver.find_elements_by_xpath('//small[@class="ellipsis"]')
        for i in n:
            name.append(i.text)
        for i in d:
            designation.append(i.text)
        for i in c:
            company.append(i.text)
        for i in s:
            skills.append(i.text)
        for i in l:
            location.append(i.text)
    except NoSuchElementException:
        loop=[name,designation,company,skills,location]
        for i in loop:
            i.append('_') 
    try:
        next_btn=driver.find_element_by_xpath('//button[2][@class="grayBtn"]')#finding the search button element using xpath
        next_btn.click()#clicking the next button
        time.sleep(2)
    except NoSuchElementException :
        break

scraping page  1
scraping page  2
scraping page  3
scraping page  4
scraping page  5
scraping page  6
scraping page  7
scraping page  8
scraping page  9
scraping page  10
scraping page  11
scraping page  12
scraping page  13
scraping page  14
scraping page  15
scraping page  16
scraping page  17
scraping page  18
scraping page  19
scraping page  20
scraping page  21
scraping page  22
scraping page  23
scraping page  24
scraping page  25
scraping page  26
scraping page  27
scraping page  28
scraping page  29
scraping page  30
scraping page  31
scraping page  32
scraping page  33
scraping page  34
scraping page  35
scraping page  36
scraping page  37
scraping page  38
scraping page  39
scraping page  40
scraping page  41
scraping page  42
scraping page  43
scraping page  44
scraping page  45
scraping page  46
scraping page  47
scraping page  48
scraping page  49
scraping page  50
scraping page  51

KeyboardInterrupt:

In [22]:
print(len(name),len(designation),len(skills),len(company),len(location))#checking the length of all thelist

2550 2550 2550 5100 2537

In [24]:
#Combining all the lists and creating a dataframe:
Name=[]
Designation=[]
Company=[]
Skills=[]
Location=[]
Name=name1+name
Designation=designation1+designation
Skills=skills1+skills
Company=company1[1:100:2]+company[1:5100:2]
Location=location1+location
df=pd.DataFrame({'Name':Name[0:2550],'Designation':Designation[0:2550],'Company':Company[0:2550],'Skills':Skills[0:2550],'Location':Location[0:2550]})
df

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
...,...,...,...,...,...
2545,Sai,Recruiter,People Gamut,Not Specified,Hyderabad / Secunderabad
2546,Rachna Rastogi,Director,Bregma Science LLP,Not Specified,Hyderabad / Secunderabad
2547,MR. SANJAY,ADMIN HEAD,Healthius Life Sciences,"Back Office, Data Entry, Office Administration...",Gurgaon
2548,Chhaya Verma,HR Specialist,Mount Talent Consulting Pvt Ltd,"Avp, Vp, Project Manager-it, Agm/dgm, Director...",Bengaluru / Bangalore
2549,Quenext,Admin,Quenext Decision Science Technology Pvt Ltd,"Big Data, Open Source, Distribution System, Bi...",Bengaluru / Bangalore

In [ ]:
driver.close()

8. Scrape the details of Highest selling novels.Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/ .You have to find the following details:

    A) Book name
    
    B) Author name
    
    C) Volumes sold
    
    D) Publisher
    
    E) Genre

In [29]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [32]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)

In [33]:
#scraping all the hightest selling novels data and framing them in lists:
Book=[]
Author=[] 
sold=[]
Publisher=[]
Genre=[]
try:
    b=driver.find_elements_by_xpath('//td[2][@class="left"]')
    a=driver.find_elements_by_xpath('//td[3][@class="left"]')
    s=driver.find_elements_by_xpath('//td[4][@class="left"]')
    p=driver.find_elements_by_xpath('//td[5][@class="left"]')
    g=driver.find_elements_by_xpath('//td[@class="last left"]')
    for i in b:
        Book.append(i.text)
    for i in a:
        Author.append(i.text)
    for i in s:
        sold.append(i.text)
    for i in p:
        Publisher.append(i.text)
    for i in g:
        Genre.append(i.text)
except NoSuchElementException:
    loop=[Book,Author,sold,Publisher,Genre]
    for i in loop:
        i.append('_')

In [34]:
print(len(Book),len(Author),len(sold),len(Publisher),len(Genre))#checking the length of all the lists

100 100 100 100 100

In [35]:
#creating a dataframe:
df=pd.DataFrame({'Book_name':Book,'Author_name':Author,'Volume_sold':sold,'Publisher':Publisher,'Genre':Genre})
df

,Book_name,Author_name,Volume_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [ ]:
driver.close()

9. Scrape the details most watched tv series of all time from imdb.com.Url = https://www.imdb.com/list/ls095964455/ .You have to find the following details:

    A) Name

    B) Year span

    C) Genre

    D) Run time

    E) Ratings

    F) Votes

In [36]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [37]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url='https://www.imdb.com/list/ls095964455/'
driver.get(url)

In [38]:
#scraping most watched tv series  and framing them in form of lists:
Name=[]
Year=[] 
Genre=[]
Runtime=[]
Ratings=[]
Votes=[]
try:
    n=driver.find_elements_by_xpath('//h3[@class="lister-item-header"]/a')
    y=driver.find_elements_by_xpath('//span[@class="lister-item-year text-muted unbold"]')
    g=driver.find_elements_by_xpath('//SPAN[@class="genre"]')
    run=driver.find_elements_by_xpath('//SPAN[@class="runtime"]')
    r=driver.find_elements_by_xpath('//DIV[@class="ipl-rating-star small"]/span[2]')
    v=driver.find_elements_by_xpath('//P[4][@class="text-muted text-small"]/span[2]')
    for i in n:
        Name.append(i.text)
    for i in y:
        Year.append(i.text)
    for i in g:
        Genre.append(i.text)
    for i in run:
        Runtime.append(i.text)
    for i in r:
        Ratings.append(i.text)
    for i in v:
        Votes.append(i.text)
except NoSuchElementException:
    loop=[Name,Year,Genre,Runtime,Ratings,Votes]
    for i in loop:
        i.append('_')

In [39]:
print(len(Name),len(Year),len(Genre),len(Runtime),len(Ratings),len(Votes))#checking length of all the lists

100 100 100 100 100 100

In [40]:
#creating a  dataframe:
df=pd.DataFrame({'Name':Name,'Year':Year,'Genre':Genre,'Runtime':Runtime,'Ratings':Ratings,'Votes':Votes})
df

,Name,Year,Genre,Runtime,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,965,354"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"973,076"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.3,"936,244"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"280,078"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.7,"240,202"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.6,"48,047"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"58,751"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.2,"186,855"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"39,605"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"223,458"

In [ ]:
driver.close()

10. Details of Datasets from UCI machine learning repositories.Url = https://archive.ics.uci.edu/ .You have to find the following details:

    A) Dataset name

    B) Data type

    C) Task

    D) Attribute type

    E) No of instances

    F) No of attribute

    G) Year

    Note: - from the home page you have to go to the ShowAllDataset page through code.

In [1]:
#importing all the necessory libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup
from selenium import webdriver  
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import re
import requests

import warnings
warnings.filterwarnings("ignore")

In [2]:
#getting the url using driver:
Path = r'C:\Users\admin\Desktop\chromedriver.exe'
driver=webdriver.Chrome(Path)
url='https://archive.ics.uci.edu/'
driver.get(url)

In [3]:
#clicking view all  the dat sets link:
view=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a')
view.click()

In [9]:
#scraping the data set names in the a bove url:
Datasetname=[]
Datatype=[]
Task=[]
Attributetype=[]
No_of_instances=[]
No_of_attribute=[]
Year=[]
dataset=driver.find_elements_by_xpath('//P[@class="normal"]/b/a')
for i in dataset:
    Datasetname.append(i.text)
len(Datasetname)

622

In [10]:
#scraping the all the urls links in the above  page
url=[]
for i in dataset:
    url.append(i.get_attribute('href'))
len(url)

622

In [13]:
#scraping all the data from the urls scrapped above
for i in url:
    driver.get(i)
    time.sleep(5)
    try:
        typ=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[1]/td[2]/p')
        task=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[3]/td[2]/p')
        att=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[2]/p')
        inst=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[1]/td[4]/p')
        natt=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[4]/p')
        year=driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/table[2]/tbody/tr[2]/td[6]/p')
        Datatype.append(typ.text)
        Task.append(task.text)
        Attributetype.append(att.text)
        No_of_instances.append(inst.text)
        No_of_attribute.append(natt.text)
        Year.append(year.text)
    except NoSuchElementException:
        loop=[Datatype,Task,Attributetype,No_of_instances,No_of_attribute,Year]
        for i in loop:
            i.append('_')

In [14]:
print(len(Datasetname),len(Datatype),len(Task),len(Attributetype),len(No_of_instances),len(No_of_attribute),len(Year))#checking the length of all lists

622 624 622 622 622 622 622

In [22]:
y=[i.split('-', 1)[0] for i in Year]#getting the year from the date list
y

['1995',
 '1996',
 'N/A',
 '1998',
 '1998',
 '1992',
 '1987',
 '1992',
 '1993',
 '1987',
 '1994',
 '1994',
 'N/A',
 '1988',
 '1992',
 '1995',
 '1995',
 '1990',
 '1997',
 '1996',
 '1988',
 '1989',
 '1994',
 'N/A',
 'N/A',
 '1995',
 'N/A',
 '1992',
 '1987',
 '1997',
 '1998',
 '1995',
 '1998',
 'N/A',
 'N/A',
 '1994',
 'N/A',
 '1989',
 '1996',
 '1990',
 '1990',
 '1987',
 '1999',
 '1989',
 '1988',
 '1988',
 '1989',
 'N/A',
 '1990',
 '1998',
 '1989',
 '1988',
 '1994',
 '1990',
 '1988',
 '1988',
 '1990',
 '1991',
 '1990',
 'N/A',
 '1992',
 '1988',
 '1990',
 '1996',
 '1995',
 '1990',
 'N/A',
 '1992',
 '1992',
 '1994',
 'N/A',
 '1987',
 '1994',
 '1994',
 '1997',
 '1991',
 '1995',
 '1998',
 '1998',
 '1993',
 '1988',
 'N/A',
 'N/A',
 '1992',
 '1993',
 '1988',
 '1989',
 '1988',
 '1987',
 '1993',
 '1988',
 '1999',
 '2001',
 '2001',
 'N/A',
 '1992',
 '1993',
 '1997',
 '1991',
 '1987',
 '1994',
 '1988',
 '1987',
 '1993',
 '1988',
 '1988',
 '1991',
 '1996',
 '1990',
 'N/A',
 '1999',
 '1999',
 '2002',
 'N/A',
 '2000',
 '1999',
 '1999',
 '2001',
 '1999',
 '1999',
 '2000',
 '1999',
 '2000',
 '1999',
 '1999',
 'N/A',
 '1998',
 '1999',
 '2001',
 '1999',
 'N/A',
 '2003',
 '1999',
 '1999',
 '1997',
 '1999',
 '1999',
 '1998',
 'N/A',
 'N/A',
 'N/A',
 '1994',
 'N/A',
 '1993',
 '1990',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 'N/A',
 '1989',
 '2006',
 '2006',
 '2007',
 '2007',
 '2007',
 '2007',
 '2008',
 '2008',
 '2008',
 '2007',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2009',
 '2008',
 '2008',
 '2008',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2010',
 '2009',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2014',
 '2013',
 '2013',
 '2013',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2013',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2015',
 '2014',
 '2014',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2014',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2016',
 '2016',
 '2015',
 '2016',
 '_',
 '2015',
 '2016',
 '2016',
 '2016',
 '2016',
 '_',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 '2017',
 '2016',
 '2017',
 '2016',
 '2017',
 '2017',
 '2016',
 '2016',
 '2017',
 '2017',
 '2016',
 '2017',
 '2017',
 '2017',
 '2017',
 '2016',
 '2017',
 '2016',
 '2016',
 '2016',
 '_',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2016',
 '2016',
 '2016',
 '2016',
 '_',
 '2017',
 '2017',
 '2017',
 '2017',
 '2016',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2016',
 '2016',
 '2016',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2016',
 '2018',
 '2018',
 '2016',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '_',
 '2018',
 '2018',
 '2019',
 '2019',
 '2018',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2020',
 '2020',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2021',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2021',
 '2020',
 '2020',
 '2020',
 '2021',
 '2020']

In [23]:
# creating a dataframe:
df=pd.DataFrame({'Dataset_name':Datasetname,
                'Data_type':Datatype[2:624],
                'Task':Task,
                'Attribute_type':Attributetype,
                'No_of_instances':No_of_instances,
                'No_of_attribute':No_of_attribute,
                'Year':y})
df

,Dataset_name,Data_type,Task,Attribute_type,No_of_instances,No_of_attribute,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,N/A
3,Anonymous Microsoft Web Data,N/A,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,N/A,Classification,N/A,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,"Univariate, Sequential, Time-Series",Regression,Real,4000,2,2020

In [ ]:
driver.close()